plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.75'
}

version = project.mod_version
group = 'kaptainwutax.seedcrackerX'

base {
    archivesName = 'seedcrackerX_neoforge'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        seedcrackerx {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    includedLibrary
    implementation.extendsFrom includedLibrary
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.shedaniel.me/' }
    maven { url = 'https://maven.seedfinding.com/' }
    maven { url = 'https://maven-snapshots.seedfinding.com/' }
    maven { url = 'https://maven.latticg.com/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}"

    includedLibrary('com.seedfinding:mc_math:ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91') { transitive = false }
    includedLibrary('com.seedfinding:mc_seed:1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409') { transitive = false }
    includedLibrary('com.seedfinding:mc_core:144493514fc9bfb735ce21838e48426625f29e43') { transitive = false }
    includedLibrary('com.seedfinding:mc_noise:7e3ba65e181796c4a2a1c8881d840b2254b92962') { transitive = false }
    includedLibrary('com.seedfinding:mc_biome:41a42cb9019a552598f12089059538853e18ec78') { transitive = false }
    includedLibrary('com.seedfinding:mc_terrain:b4246cbd5880c4f8745ccb90e1b102bde3448126') { transitive = false }
    includedLibrary('com.seedfinding:mc_feature:919b7e513cc1e87e029a9cd703fc4e2dc8686229') { transitive = false }
    includedLibrary('com.seedfinding:mc_reversal:ca64c0890c106f1a2207623c316fce86f250b918') { transitive = false }
    includedLibrary('com.seedfinding:latticg:1.06')
}

tasks.named('jar', Jar) {
    from(configurations.includedLibrary.collect { it.isDirectory() ? it : zipTree(it) }) {
        include 'com/seedfinding/**'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
