org.gradle.jvmargs=-Xmx3G

# Mod Properties
mod_id=seedcrackerx
mod_name=SeedcrackerX
mod_license=MIT
mod_version=2.15.0
mod_authors=19MisterX98, KaptainWutax
mod_description=In-game seed cracker mod for Minecraft

# NeoForge and Minecraft dependencies
neoforge_version=21.1.86
minecraft_version=1.21.1
cloth_config_version=15.0.130

# Java Toolchain
java_version=21
